name: Build & Deploy

on:
  push:
    branches:
      - master

env:
  REGISTRY_NAME: gielniakcontainerregistry.azurecr.io
  IMAGE_NAME: fastapi-test
  TF_DIR: ./terraform

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check variables
        run: echo ${{ env.REGISTRY_NAME }} ${{ env.IMAGE_NAME }} ${{ env.TF_DIR }}

      - name: Log in to ACR
        run: az acr login --name ${{ env.REGISTRY_NAME }}

      - name: Set image tag
        id: set-tag
        run: echo "image-tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build and push image
        run: |
          ls
          cd backend
          docker build -t ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.image-tag }} .
          docker push ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.image-tag }}
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}

  deploy-dev:
    needs: build
    uses: ./.github/workflows/deployment-template.yaml
    secrets: inherit
    with:
      environment: dev
      image_tag: ${{ needs.build.outputs.image-tag }}
      registry_name: gielniakcontainerregistry.azurecr.io
      image_name: fastapi-test
      tf_dir: ./terraform

  deploy-staging:
    needs: [build, deploy-dev]
    uses: ./.github/workflows/deployment-template.yaml
    secrets: inherit
    with:
      environment: staging
      image_tag: ${{ needs.build.outputs.image-tag }}
      registry_name: gielniakcontainerregistry.azurecr.io
      image_name: fastapi-test
      tf_dir: ./terraform

  deploy-prod:
    needs: [build, deploy-staging]
    uses: ./.github/workflows/deployment-template.yaml
    secrets: inherit
    with:
      environment: prod
      image_tag: ${{ needs.build.outputs.image-tag }}
      registry_name: gielniakcontainerregistry.azurecr.io
      image_name: fastapi-test
      tf_dir: ./terraform
  